apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: crossplane-poc-cluster
  region: eu-west-3
  version: "1.29"

nodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 2
    volumeSize: 80
